# Generated by Django 5.0.1 on 2024-02-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_alter_joke_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
